import Foundation
import UIKit
import MoonKit

NSMetadataItemIsUbiquitousKey
NSMetadataUbiquitousItemHasUnresolvedConflictsKey
NSMetadataUbiquitousItemIsDownloadingKey
NSMetadataUbiquitousItemIsUploadedKey
NSMetadataUbiquitousItemIsUploadingKey
NSMetadataUbiquitousItemPercentDownloadedKey
NSMetadataUbiquitousItemPercentUploadedKey
NSMetadataUbiquitousItemDownloadingStatusKey
NSMetadataUbiquitousItemDownloadingErrorKey
NSMetadataUbiquitousItemUploadingErrorKey
