//
//  MoonKit.h
//  MoonKit
//
//  Created by Jason Cardwell on 9/15/14.
//  Copyright (c) 2014 Jason Cardwell. All rights reserved.
//

@import UIKit;

//! Project version number for MoonKit.
FOUNDATION_EXPORT double MoonKitVersionNumber;

//! Project version string for MoonKit.
FOUNDATION_EXPORT const unsigned char MoonKitVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <MoonKit/PublicHeader.h>
//#import <MoonKit/MSKitDefines.h>
//#import <MoonKit/CALayer+MSKitAdditions.h>
//#import <MoonKit/MSPopupBarButton.h>
//#import <MoonKit/NSArray+MSKitAdditions.h>
//#import <MoonKit/MSScrollWheel.h>
//#import <MoonKit/NSAssertionHandler+MSKitAdditions.h>
//#import <MoonKit/MSKitGeometryFunctions.h>
////#import <MoonKit/NSAttributedString+MSKitAdditions.h>
//#import <MoonKit/MSKitLoggingFunctions.h>
//#import <MoonKit/NSDictionary+MSKitAdditions.h>
//#import <MoonKit/MSKitMiscellaneousFunctions.h>
//#import <MoonKit/NSFetchRequest+MSKitAdditions.h>
//#import <MoonKit/MSGestureManager.h>
//#import <MoonKit/NSFetchedResultsController+MSKitAdditions.h>
//#import <MoonKit/MSLongPressGestureRecognizer.h>
//#import <MoonKit/NSHashTable+MSKitAdditions.h>
//#import <MoonKit/MSMultiselectGestureRecognizer.h>
//#import <MoonKit/MSPinchGestureRecognizer.h>
//#import <MoonKit/NSManagedObject+MSKitAdditions.h>
//#import <MoonKit/MSSwipeGestureRecognizer.h>
//#import <MoonKit/NSManagedObjectContext+MSKitAdditions.h>
//#import <MoonKit/MSResizingLayer.h>
//#import <MoonKit/NSMapTable+MSKitAdditions.h>
//#import <MoonKit/NSNull+MSKitAdditions.h>
//#import <MoonKit/MSKitMacros.h>
//#import <MoonKit/NSNumber+MSKitAdditions.h>
//#import <MoonKit/MSAssertionHandler.h>
//#import <MoonKit/NSObject+MSKitAdditions.h>
//#import <MoonKit/MSBitVector.h>
//#import <MoonKit/NSOperationQueue+MSKitAdditions.h>
//#import <MoonKit/MSCompletionBlockOperation.h>
//#import <MoonKit/NSOrderedSet+MSKitAdditions.h>
//#import <MoonKit/MSContextChangeReceptionist.h>
//#import <MoonKit/NSPointerArray+MSKitAdditions.h>
//#import <MoonKit/MSDictionary.h>
//#import <MoonKit/MSDictionaryIndex.h>
//#import <MoonKit/NSSet+MSKitAdditions.h>
//#import <MoonKit/MSError.h>
//#import <MoonKit/NSString+MSKitAdditions.h>
//#import <MoonKit/NSMutableString+MSKitAdditions.h>
//#import <MoonKit/NSURL+MSKitAdditions.h>
//#import <MoonKit/NSUserDefaults+MSKitAdditions.h>
//#import <MoonKit/NSValue+MSKitAdditions.h>
//#import <MoonKit/MSKVOReceptionist.h>
//#import <MoonKit/MSLog.h>
////#import <MoonKit/UIAlertView+MSKitAdditions.h>
//#import <MoonKit/MSLogMacros.h>
//#import <MoonKit/UICollectionViewFlowLayout+MSKitAdditions.h>
//#import <MoonKit/MSNetworkReachability.h>
//#import <MoonKit/UIColor+MSKitAdditions.h>
//#import <MoonKit/MSPainter.h>
//#import <MoonKit/UIControl+MSKitAdditions.h>
//#import <MoonKit/MSQueue.h>
//#import <MoonKit/MSXMLParserDelegate.h>
//#import <MoonKit/MSKeyPath.h>
//#import <MoonKit/UIFont+MSKitAdditions.h>
//#import <MoonKit/MSSingleton.h>
//#import <MoonKit/UIGestureRecognizer+MSKitAdditions.h>
//#import <MoonKit/MSSingletonController.h>
//#import <MoonKit/UIImage+ImageEffects.h>
//#import <MoonKit/MSStack.h>
//#import <MoonKit/UIImage+MSKitAdditions.h>
//#import <MoonKit/MSValueTransformers.h>
//#import <MoonKit/UIStoryboard+MSKitAdditions.h>
//#import <MoonKit/MSKitProtocols.h>
//#import <MoonKit/UITableView+MSKitAdditions.h>
//#import <MoonKit/MSCheckboxView.h>
////#import <MoonKit/UIView+MSKitAdditions.h>
//#import <MoonKit/MSColorInputView.h>
//#import <MoonKit/NSIndexPath+MSKitAdditions.h>
//#import <MoonKit/UIViewController+MSKitAdditions.h>
//#import <MoonKit/MSMultiselectView.h>
//#import <MoonKit/UIWindow+MSKitAdditions.h>
//#import <MoonKit/MSNumberPadView.h>
//#import <MoonKit/MSColorInputViewController.h>
//#import <MoonKit/MSPickerInputView.h>
//#import <MoonKit/MSPickerInputViewController.h>
//#import <MoonKit/MSReflectingView.h>
//#import <MoonKit/MSBarButtonItem.h>
//#import <MoonKit/MSReplicatorView.h>
//#import <MoonKit/MSTouchReporterView.h>
//#import <MoonKit/MSColorInputButton.h>
//#import <MoonKit/MSView.h>
//#import <MoonKit/MSPickerInputButton.h>
//#import <MoonKit/MSNotificationReceptionist.h>
//#import <MoonKit/GCDAsyncSocket.h>
//#import <MoonKit/GCDAsyncUdpSocket.h>
//#import <MoonKit/MSBarButtonItem_Private.h>
//#import <MoonKit/MSPopupBarButton_Private.h>
#import "MSKitDefines.h"
#import "CALayer+MSKitAdditions.h"
#import "MSPopupBarButton.h"
#import "NSArray+MSKitAdditions.h"
#import "MSScrollWheel.h"
#import "NSAssertionHandler+MSKitAdditions.h"
#import "MSKitGeometryFunctions.h"
//#import "NSAttributedString+MSKitAdditions.h"
#import "MSKitLoggingFunctions.h"
#import "NSDictionary+MSKitAdditions.h"
#import "MSKitMiscellaneousFunctions.h"
#import "NSFetchRequest+MSKitAdditions.h"
#import "MSGestureManager.h"
#import "NSFetchedResultsController+MSKitAdditions.h"
#import "MSLongPressGestureRecognizer.h"
#import "NSHashTable+MSKitAdditions.h"
#import "MSMultiselectGestureRecognizer.h"
#import "MSPinchGestureRecognizer.h"
#import "NSManagedObject+MSKitAdditions.h"
#import "MSSwipeGestureRecognizer.h"
#import "NSManagedObjectContext+MSKitAdditions.h"
#import "MSResizingLayer.h"
#import "NSMapTable+MSKitAdditions.h"
#import "NSNull+MSKitAdditions.h"
#import "MSKitMacros.h"
#import "NSNumber+MSKitAdditions.h"
#import "MSAssertionHandler.h"
#import "NSObject+MSKitAdditions.h"
#import "MSBitVector.h"
#import "NSOperationQueue+MSKitAdditions.h"
#import "MSCompletionBlockOperation.h"
#import "NSOrderedSet+MSKitAdditions.h"
#import "MSContextChangeReceptionist.h"
#import "NSPointerArray+MSKitAdditions.h"
#import "MSDictionary.h"
#import "MSDictionaryIndex.h"
#import "NSSet+MSKitAdditions.h"
#import "MSError.h"
#import "NSString+MSKitAdditions.h"
#import "NSMutableString+MSKitAdditions.h"
#import "NSURL+MSKitAdditions.h"
#import "NSUserDefaults+MSKitAdditions.h"
#import "NSValue+MSKitAdditions.h"
#import "MSKVOReceptionist.h"
#import "MSLog.h"
//#import "UIAlertView+MSKitAdditions.h"
#import "MSLogMacros.h"
#import "UICollectionViewFlowLayout+MSKitAdditions.h"
#import "MSNetworkReachability.h"
#import "UIColor+MSKitAdditions.h"
#import "MSPainter.h"
#import "UIControl+MSKitAdditions.h"
#import "MSQueue.h"
#import "MSXMLParserDelegate.h"
#import "MSKeyPath.h"
#import "UIFont+MSKitAdditions.h"
#import "MSSingleton.h"
#import "UIGestureRecognizer+MSKitAdditions.h"
#import "MSSingletonController.h"
#import "UIImage+ImageEffects.h"
#import "MSStack.h"
#import "UIImage+MSKitAdditions.h"
#import "MSValueTransformers.h"
#import "UIStoryboard+MSKitAdditions.h"
#import "MSKitProtocols.h"
#import "UITableView+MSKitAdditions.h"
#import "MSCheckboxView.h"
//#import "UIView+MSKitAdditions.h"
#import "MSColorInputView.h"
#import "NSIndexPath+MSKitAdditions.h"
#import "UIViewController+MSKitAdditions.h"
#import "MSMultiselectView.h"
#import "UIWindow+MSKitAdditions.h"
#import "MSNumberPadView.h"
#import "MSColorInputViewController.h"
#import "MSPickerInputView.h"
#import "MSPickerInputViewController.h"
#import "MSReflectingView.h"
#import "MSBarButtonItem.h"
#import "MSReplicatorView.h"
#import "MSTouchReporterView.h"
#import "MSColorInputButton.h"
#import "MSView.h"
#import "MSPickerInputButton.h"
#import "MSNotificationReceptionist.h"
#import "GCDAsyncSocket.h"
#import "GCDAsyncUdpSocket.h"
#import "MSBarButtonItem_Private.h"
#import "MSPopupBarButton_Private.h"
